version: "3.9"

services:
  db:
    image: postgres:13-alpine3.18
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./demo.sql:/demo.sql
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports: ["5432:5432"]
    networks:
      - postgres
    restart: no
    shm_size: 1G
#   pg_admin:
#     image: dpage/pgadmin4
#     restart: no
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: root
#     ports: ["80:80"]
#     volumes:
#       - ./pg_pgadmin/:/var/lib/pgadmin
#     networks:
#       - postgres

volumes:
  pg_pgadmin:

networks:
  postgres:
    driver: bridge